framework:
  exceptions:
    Doctrine\ORM\OptimisticLockException:
      status_code: 409
      log_level: warning

    Doctrine\DBAL\Exception\UniqueConstraintViolationException:
      status_code: 409
      log_level: warning