nelmio_api_doc:
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc)
    documentation:
        info:
            title: Expense Tracker API
            description: Api Endpoints Docs
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []