auth_controllers:
    resource:
        path: ../src/Auth/Controller/
        namespace: App\Auth\Controller
    type: attribute

session_controllers:
    resource:
        path: ../src/Session/Controller/
        namespace: App\Session\Controller
    type: attribute

wallet_controllers:
    resource:
        path: ../src/Wallet/Controller/
        namespace: App\Wallet\Controller
    type: attribute
