auth_controllers:
    resource:
        path: ../src/Auth/Controller/
        namespace: App\Auth\Controller
    type: attribute

session_controllers:
    resource:
        path: ../src/Session/Controller/
        namespace: App\Session\Controller
    type: attribute

wallet_controllers:
    resource:
        path: ../src/Wallet/Controller/
        namespace: App\Wallet\Controller
    type: attribute


category_controllers:
    resource:
        path: ../src/Category/Controller/
        namespace: App\Category\Controller
    type: attribute

transaction_controllers:
    resource:
        path: ../src/Transaction/Controller/
        namespace: App\Transaction\Controller
    type: attribute

budget_controllers:
    resource:
        path: ../src/Budget/Controller/
        namespace: App\Budget\Controller
    type: attribute

analytics_controllers:
    resource:
        path: ../src/Analytics/Controller/
        namespace: App\Analytics\Controller
    type: attribute