# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # 1. Najpierw auto-discovery dla wszystkiego
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Auth\Service\LoginRateLimiter:
        arguments:
            $loginLimiter: '@limiter.login'

    App\Auth\Factory\CookieFactory:
        arguments:
            - '%env(bool:AUTH_COOKIE_SECURE)%'

    App\Auth\EventListener\DebugAuthListener:
        arguments:
            $logPath: '%kernel.logs_dir%/cookie.log'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\Auth\Security\CookieTokenExtractor:
        tags:
            - { name: 'lexik_jwt.token_extractor' }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
