# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Auth\Service\LoginRateLimiter:
        arguments:
            $loginLimiter: '@limiter.login'

    App\Auth\Factory\CookieFactory:
        arguments:
            - '%env(bool:AUTH_COOKIE_SECURE)%'

    App\Auth\EventListener\DebugAuthListener:
        arguments:
            $logPath: '%kernel.logs_dir%/cookie.log'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\Auth\Security\CookieTokenExtractor: ~

    app.jwt_cookie_authenticator:
        class: App\Auth\Security\CookieJWTAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator

    App\Session\Service\CurrentSessionResolver:
        arguments:
            $logPath: '%kernel.logs_dir%/current_session_resolver.log'